export class SharedConstants {
  // public static parkingModels = {
  //   parter: [
  //     {
  //       sizeRow: 11,
  //       sizeCol: 17,
  //       name: 'Area 1',
  //       spots: [
  //         {
  //           y: 2,
  //           x: 2,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 1,
  //         },
  //         {
  //           y: 3,
  //           x: 2,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 2,
  //         },
  //         {
  //           y: 4,
  //           x: 2,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 3,
  //         },
  //         {
  //           y: 5,
  //           x: 2,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 4,
  //         },
  //         {
  //           y: 6,
  //           x: 2,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 5,
  //         },
  //         {
  //           y: 7,
  //           x: 2,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 6,
  //         },
  //         {
  //           y: 8,
  //           x: 2,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 7,
  //         },
  //         {
  //           y: 9,
  //           x: 2,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 8,
  //         },
  //         {
  //           y: 1,
  //           x: 6,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 9,
  //         },
  //         {
  //           y: 2,
  //           x: 6,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 10,
  //         },
  //         {
  //           y: 3,
  //           x: 6,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 11,
  //         },
  //         {
  //           y: 4,
  //           x: 6,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 12,
  //         },
  //         {
  //           y: 5,
  //           x: 6,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 13,
  //         },
  //         {
  //           y: 6,
  //           x: 6,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 14,
  //         },
  //         {
  //           y: 7,
  //           x: 6,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 15,
  //         },
  //         {
  //           y: 8,
  //           x: 6,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 16,
  //         },
  //         {
  //           y: 9,
  //           x: 6,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 17,
  //         },
  //         {
  //           y: 1,
  //           x: 8,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 18,
  //         },
  //         {
  //           y: 2,
  //           x: 8,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 19,
  //         },
  //         {
  //           y: 3,
  //           x: 8,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 20,
  //         },
  //         {
  //           y: 4,
  //           x: 8,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 21,
  //         },
  //         {
  //           y: 5,
  //           x: 8,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 22,
  //         },
  //         {
  //           y: 6,
  //           x: 8,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 23,
  //         },
  //         {
  //           y: 7,
  //           x: 8,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 24,
  //         },
  //         {
  //           y: 8,
  //           x: 8,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 25,
  //         },
  //         {
  //           y: 9,
  //           x: 8,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 26,
  //         },

  //         {
  //           y: 1,
  //           x: 12,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 27,
  //         },
  //         {
  //           y: 2,
  //           x: 12,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 28,
  //         },
  //         {
  //           y: 3,
  //           x: 12,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 29,
  //         },
  //         {
  //           y: 4,
  //           x: 12,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 30,
  //         },
  //         {
  //           y: 5,
  //           x: 12,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 31,
  //         },
  //         {
  //           y: 6,
  //           x: 12,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 32,
  //         },
  //         {
  //           y: 7,
  //           x: 12,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 33,
  //         },
  //         {
  //           y: 8,
  //           x: 12,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 34,
  //         },
  //         {
  //           y: 9,
  //           x: 12,
  //           orientation: 'horizontal-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 35,
  //         },
  //         {
  //           y: 1,
  //           x: 14,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 36,
  //         },
  //         {
  //           y: 2,
  //           x: 14,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 37,
  //         },
  //         {
  //           y: 3,
  //           x: 14,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 38,
  //         },
  //         {
  //           y: 4,
  //           x: 14,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 39,
  //         },
  //         {
  //           y: 5,
  //           x: 14,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 40,
  //         },
  //         {
  //           y: 6,
  //           x: 14,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 41,
  //         },
  //         {
  //           y: 7,
  //           x: 14,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 42,
  //         },
  //         {
  //           y: 8,
  //           x: 14,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 43,
  //         },
  //         {
  //           y: 9,
  //           x: 14,
  //           orientation: 'horizontal-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 44,
  //         },
  //       ],
  //     },
  //     {
  //       sizeRow: 11,
  //       sizeCol: 17,
  //       name: 'Area 2',
  //       spots: [
  //         {
  //           y: 0,
  //           x: 1,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 1,
  //         },
  //         {
  //           y: 0,
  //           x: 2,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 2,
  //         },
  //         {
  //           y: 0,
  //           x: 3,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 3,
  //         },
  //         {
  //           y: 0,
  //           x: 4,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 4,
  //         },
  //         {
  //           y: 0,
  //           x: 5,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 5,
  //         },
  //         {
  //           y: 0,
  //           x: 6,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 6,
  //         },

  //         {
  //           y: 0,
  //           x: 7,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 7,
  //         },
  //         {
  //           y: 0,
  //           x: 8,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 8,
  //         },
  //         {
  //           y: 0,
  //           x: 9,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 9,
  //         },
  //         {
  //           y: 0,
  //           x: 10,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 10,
  //         },
  //         {
  //           y: 0,
  //           x: 11,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 11,
  //         },
  //         {
  //           y: 0,
  //           x: 12,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 12,
  //         },
  //         {
  //           y: 0,
  //           x: 13,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 13,
  //         },
  //         {
  //           y: 0,
  //           x: 14,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 14,
  //         },
  //         {
  //           y: 0,
  //           x: 15,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 15,
  //         },
  //         {
  //           y: 4,
  //           x: 1,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 16,
  //         },
  //         {
  //           y: 4,
  //           x: 2,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 17,
  //         },
  //         {
  //           y: 4,
  //           x: 3,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 18,
  //         },
  //         {
  //           y: 4,
  //           x: 4,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 19,
  //         },
  //         {
  //           y: 4,
  //           x: 5,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 20,
  //         },
  //         {
  //           y: 4,
  //           x: 6,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 21,
  //         },
  //         {
  //           y: 4,
  //           x: 7,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 22,
  //         },
  //         {
  //           y: 4,
  //           x: 8,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 23,
  //         },
  //         {
  //           y: 4,
  //           x: 9,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 24,
  //         },
  //         {
  //           y: 4,
  //           x: 10,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 25,
  //         },
  //         {
  //           y: 4,
  //           x: 11,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 26,
  //         },
  //         {
  //           y: 4,
  //           x: 12,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 27,
  //         },
  //         {
  //           y: 4,
  //           x: 13,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 28,
  //         },
  //         {
  //           y: 4,
  //           x: 14,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 29,
  //         },
  //         {
  //           y: 4,
  //           x: 15,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 30,
  //         },
  //         {
  //           y: 6,
  //           x: 1,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 31,
  //         },
  //         {
  //           y: 6,
  //           x: 2,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 32,
  //         },
  //         {
  //           y: 6,
  //           x: 3,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 33,
  //         },
  //         {
  //           y: 6,
  //           x: 4,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 34,
  //         },
  //         {
  //           y: 6,
  //           x: 5,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 35,
  //         },
  //         {
  //           y: 6,
  //           x: 6,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 36,
  //         },
  //         {
  //           y: 6,
  //           x: 7,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 37,
  //         },
  //         {
  //           y: 6,
  //           x: 8,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 38,
  //         },
  //         {
  //           y: 6,
  //           x: 9,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 39,
  //         },
  //         {
  //           y: 6,
  //           x: 10,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 40,
  //         },
  //         {
  //           y: 6,
  //           x: 11,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 41,
  //         },
  //         {
  //           y: 6,
  //           x: 12,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 42,
  //         },
  //         {
  //           y: 6,
  //           x: 13,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 43,
  //         },
  //         {
  //           y: 6,
  //           x: 14,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 44,
  //         },
  //         {
  //           y: 6,
  //           x: 15,
  //           orientation: 'vertical-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 45,
  //         },
  //         {
  //           y: 10,
  //           x: 1,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 46,
  //         },
  //         {
  //           y: 10,
  //           x: 2,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 47,
  //         },
  //         {
  //           y: 10,
  //           x: 3,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 48,
  //         },
  //         {
  //           y: 10,
  //           x: 4,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 49,
  //         },
  //         {
  //           y: 10,
  //           x: 5,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 50,
  //         },
  //         {
  //           y: 10,
  //           x: 6,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 51,
  //         },
  //         {
  //           y: 10,
  //           x: 7,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 52,
  //         },
  //         {
  //           y: 10,
  //           x: 8,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 53,
  //         },
  //         {
  //           y: 10,
  //           x: 9,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 54,
  //         },
  //         {
  //           y: 10,
  //           x: 10,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 55,
  //         },
  //         {
  //           y: 10,
  //           x: 11,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 56,
  //         },
  //         {
  //           y: 10,
  //           x: 12,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 57,
  //         },
  //         {
  //           y: 10,
  //           x: 13,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 58,
  //         },
  //         {
  //           y: 10,
  //           x: 14,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 59,
  //         },
  //         {
  //           y: 10,
  //           x: 15,
  //           orientation: 'vertical-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 60,
  //         },
  //       ],
  //     },
  //     {
  //       sizeRow: 13,
  //       sizeCol: 17,
  //       name: 'Area 3',
  //       spots: [
  //         {
  //           y: 4,
  //           x: 2,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 1,
  //         },
  //         {
  //           y: 2,
  //           x: 2,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 2,
  //         },
  //         {
  //           y: 4,
  //           x: 3,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 3,
  //         },
  //         {
  //           y: 2,
  //           x: 3,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 4,
  //         },
  //         {
  //           y: 4,
  //           x: 4,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 5,
  //         },
  //         {
  //           y: 2,
  //           x: 4,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 6,
  //         },
  //         {
  //           y: 4,
  //           x: 5,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 7,
  //         },
  //         {
  //           y: 2,
  //           x: 5,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 8,
  //         },
  //         {
  //           y: 4,
  //           x: 6,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 9,
  //         },
  //         {
  //           y: 2,
  //           x: 6,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 10,
  //         },
  //         {
  //           y: 4,
  //           x: 7,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 11,
  //         },
  //         {
  //           y: 2,
  //           x: 7,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 12,
  //         },
  //         {
  //           y: 4,
  //           x: 8,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 13,
  //         },
  //         {
  //           y: 2,
  //           x: 8,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 14,
  //         },
  //         {
  //           y: 4,
  //           x: 9,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 15,
  //         },
  //         {
  //           y: 2,
  //           x: 9,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 16,
  //         },
  //         {
  //           y: 4,
  //           x: 10,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 17,
  //         },
  //         {
  //           y: 2,
  //           x: 10,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 18,
  //         },
  //         {
  //           y: 4,
  //           x: 11,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 19,
  //         },
  //         {
  //           y: 2,
  //           x: 11,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 20,
  //         },
  //         {
  //           y: 4,
  //           x: 12,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 21,
  //         },
  //         {
  //           y: 2,
  //           x: 12,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 22,
  //         },
  //         {
  //           y: 4,
  //           x: 13,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 23,
  //         },
  //         {
  //           y: 2,
  //           x: 13,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 24,
  //         },
  //         {
  //           y: 2,
  //           x: 14,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 25,
  //         },
  //         {
  //           y: 4,
  //           x: 14,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 26,
  //         },
  //         {
  //           y: 8,
  //           x: 2,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 27,
  //         },
  //         {
  //           y: 10,
  //           x: 2,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 28,
  //         },
  //         {
  //           y: 8,
  //           x: 3,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 29,
  //         },
  //         {
  //           y: 10,
  //           x: 3,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 30,
  //         },
  //         {
  //           y: 8,
  //           x: 4,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 31,
  //         },
  //         {
  //           y: 10,
  //           x: 4,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 32,
  //         },
  //         {
  //           y: 8,
  //           x: 5,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 33,
  //         },
  //         {
  //           y: 10,
  //           x: 5,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 34,
  //         },
  //         {
  //           y: 8,
  //           x: 6,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 35,
  //         },
  //         {
  //           y: 10,
  //           x: 6,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 36,
  //         },
  //         {
  //           y: 8,
  //           x: 7,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 37,
  //         },
  //         {
  //           y: 10,
  //           x: 7,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 38,
  //         },
  //         {
  //           y: 8,
  //           x: 8,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 39,
  //         },
  //         {
  //           y: 10,
  //           x: 8,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 40,
  //         },
  //         {
  //           y: 8,
  //           x: 9,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 41,
  //         },
  //         {
  //           y: 10,
  //           x: 9,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 42,
  //         },
  //         {
  //           y: 8,
  //           x: 10,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 43,
  //         },
  //         {
  //           y: 10,
  //           x: 10,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 44,
  //         },
  //         {
  //           y: 8,
  //           x: 11,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 45,
  //         },
  //         {
  //           y: 10,
  //           x: 11,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 46,
  //         },
  //         {
  //           y: 8,
  //           x: 12,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 47,
  //         },
  //         {
  //           y: 10,
  //           x: 12,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 48,
  //         },
  //         {
  //           y: 8,
  //           x: 13,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 49,
  //         },
  //         {
  //           y: 10,
  //           x: 13,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 50,
  //         },
  //         {
  //           y: 10,
  //           x: 14,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 51,
  //         },
  //         {
  //           y: 8,
  //           x: 14,
  //           orientation: 'counterclockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 52,
  //         },
  //       ],
  //     },
  //     {
  //       sizeRow: 11,
  //       sizeCol: 17,
  //       name: 'Area 4',
  //       spots: [
  //         {
  //           y: 0,
  //           x: 2,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: false,
  //           memberId: '',
  //           indicator: 1,
  //         },
  //         {
  //           y: 0,
  //           x: 3,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 2,
  //         },
  //         {
  //           y: 0,
  //           x: 4,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: false,
  //           memberId: '',
  //           indicator: 3,
  //         },
  //         {
  //           y: 0,
  //           x: 5,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 4,
  //         },
  //         {
  //           y: 0,
  //           x: 6,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: false,
  //           memberId: '',
  //           indicator: 5,
  //         },
  //         {
  //           y: 0,
  //           x: 7,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 6,
  //         },
  //         {
  //           y: 0,
  //           x: 8,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 7,
  //         },
  //         {
  //           y: 0,
  //           x: 9,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 8,
  //         },
  //         {
  //           y: 0,
  //           x: 10,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 9,
  //         },
  //         {
  //           y: 0,
  //           x: 11,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 10,
  //         },
  //         {
  //           y: 0,
  //           x: 12,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 11,
  //         },
  //         {
  //           y: 0,
  //           x: 13,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 12,
  //         },
  //         {
  //           y: 0,
  //           x: 14,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 13,
  //         },
  //         {
  //           y: 4,
  //           x: 2,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 14,
  //         },
  //         {
  //           y: 4,
  //           x: 3,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 15,
  //         },
  //         {
  //           y: 4,
  //           x: 4,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 16,
  //         },
  //         {
  //           y: 4,
  //           x: 5,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 17,
  //         },
  //         {
  //           y: 4,
  //           x: 6,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 18,
  //         },
  //         {
  //           y: 4,
  //           x: 7,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 19,
  //         },
  //         {
  //           y: 4,
  //           x: 8,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 20,
  //         },
  //         {
  //           y: 4,
  //           x: 9,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 21,
  //         },
  //         {
  //           y: 4,
  //           x: 10,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 22,
  //         },
  //         {
  //           y: 4,
  //           x: 11,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 23,
  //         },
  //         {
  //           y: 4,
  //           x: 12,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 24,
  //         },
  //         {
  //           y: 4,
  //           x: 13,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 25,
  //         },
  //         {
  //           y: 4,
  //           x: 14,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 26,
  //         },
  //         {
  //           y: 6,
  //           x: 2,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 27,
  //         },
  //         {
  //           y: 6,
  //           x: 3,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 28,
  //         },
  //         {
  //           y: 6,
  //           x: 4,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 29,
  //         },
  //         {
  //           y: 6,
  //           x: 5,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 30,
  //         },
  //         {
  //           y: 6,
  //           x: 6,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 31,
  //         },
  //         {
  //           y: 6,
  //           x: 7,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 32,
  //         },
  //         {
  //           y: 6,
  //           x: 8,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 33,
  //         },
  //         {
  //           y: 6,
  //           x: 9,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 34,
  //         },
  //         {
  //           y: 6,
  //           x: 10,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 35,
  //         },
  //         {
  //           y: 6,
  //           x: 11,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 36,
  //         },
  //         {
  //           y: 6,
  //           x: 12,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 37,
  //         },
  //         {
  //           y: 6,
  //           x: 13,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,

  //           memberId: '',
  //           indicator: 38,
  //         },
  //         {
  //           y: 6,
  //           x: 14,
  //           orientation: 'clockwise-cell',
  //           border: 'border-top',
  //           active: true,
  //           memberId: '',
  //           indicator: 39,
  //         },
  //         {
  //           y: 10,
  //           x: 2,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 40,
  //         },
  //         {
  //           y: 10,
  //           x: 3,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 41,
  //         },
  //         {
  //           y: 10,
  //           x: 4,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 42,
  //         },
  //         {
  //           y: 10,
  //           x: 5,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 43,
  //         },
  //         {
  //           y: 10,
  //           x: 6,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 44,
  //         },
  //         {
  //           y: 10,
  //           x: 7,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 45,
  //         },
  //         {
  //           y: 10,
  //           x: 8,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 46,
  //         },
  //         {
  //           y: 10,
  //           x: 9,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 47,
  //         },
  //         {
  //           y: 10,
  //           x: 10,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 48,
  //         },
  //         {
  //           y: 10,
  //           x: 11,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 49,
  //         },
  //         {
  //           y: 10,
  //           x: 12,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 50,
  //         },
  //         {
  //           y: 10,
  //           x: 13,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 51,
  //         },
  //         {
  //           y: 10,
  //           x: 14,
  //           orientation: 'clockwise-cell',
  //           border: 'border-bottom',
  //           active: true,
  //           memberId: '',
  //           indicator: 52,
  //         },
  //       ],
  //     },
  //   ],
  // };

  public static parkingModels = [
    {
      id: null,
      name: 'Supermarket',
      address: '',
      totalLevels: 1,
      totalSpots: 52,
      freeSpots: 0,
      usedSpots: 0,
      startDate: '',
      endDate: '',
      userId: 1,
      parkingAreas: [
        {
          id: null,
          name: 'Area 1',
          sizeY: 11,
          sizeX: 17,
          totalSpots: 52,
          usedSpots: 0,
          freeSpots: 52,
          parkingEntriesId: null,
        },
      ],
      parkingEntries: [
        {
          id: null,
          name: 'Parter',
          status: '',
          parkingId: null,
          areas: null,
        },
      ],
      spots: [
        {
          y: 2,
          x: 2,
          orientation: 'horizontal-cell',
          border: 'border-bottom',
          active: true,
          indicator: 1,
          parkingAreaId: '',
        },
        {
          y: 3,
          x: 2,
          orientation: 'horizontal-cell',
          border: 'border-bottom',
          active: true,
          indicator: 2,
          parkingAreaId: '',
        },
      ],
    },
  ];

  public static defaultModels = [
    {
      name: 'Custom parking',
      totalSpots: 60,
      description:
        'An empty area which can be used to create a new custom parking.',
      image: 'parking_area_4',
    },
    {
      name: 'Supermarket',
      totalSpots: 52,
      description: 'Greater angled parking with one-way or two-way traffic.',
      image: 'parking_area_1',
    },
    {
      name: 'Office',
      totalSpots: 60,
      description: 'Perpendicular parking with one-way or two-way traffic.',
      image: 'parking_area_2',
    },
    {
      name: 'Mall',
      totalSpots: 51,
      description: 'Greater angled parking with one-way or two-way traffic.',
      image: 'parking_area_3',
    },
  ];

  public static dateLongFormat = 'MM.DD.YYYY h:mm a';
}
